# Run the `npx wrangler kv namespace create sonicjs` command and copy the id below
# Run the `npx wrangler kv namespace create sonicjs --preview` command and copy the preview_id below
# Only update the preview_id and id, leave the binding name as "KVDATA"
kv_namespaces = [
  { binding = "KV", preview_id="CHANGEME", id = "CHANGEME" }
]

# Run the `npx wrangler d1 create sonicjs` command and copy the id below to the database_id field
[[d1_databases]]
binding = "D1"
database_name = "sonicjs"
database_id = "CHANGEME"

[vars]
DISABLED_CACHE = true
RESEND_API_KEY = "re_???"
EMAIL_FROM="me@somewhere.com"
EMAIL_BASE_URL="https://sonicjs.com"
EMAIL_FROM_NAME="SonicJS"
EMAIL_CLIENT_TOKEN="???"
INVALIDATE_USER_SESSIONS = false # set to true if you want user to only login in one browser at a time

ONE_TIME_PASSWORD_EXPIRATION_TIME = 3600000 # 1 hour in milliseconds
ONE_TIME_PASSWORD_CHARACTER_LENGTH = 5

