# Run the `wrangler kv:namespace create sonicjs` command and copy the id below
# Run the `wrangler kv:namespace create sonicjs --preview` command and copy the preview_id below
# Only update the preview_id and id, leave the binding name as "KVDATA"
kv_namespaces = [
  { binding = "KV", preview_id="?????", id = "?????" }
]

# Run the `wrangler d1 create sonicjs` command and copy the id below
[[d1_databases]]
binding = "D1"
database_name = "sonicjs"
database_id = "?????"